# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180718_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='membership_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
