# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180721_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name=tinymce.models.HTMLField()),
        ),
    ]
